## tensorflow

In [1]:
# Importing the TensorFlow library
import tensorflow as tf  # Import TensorFlow

In [2]:
# Creating tensors
# Create a 1D tensor (vector) with values from 0 to 4
tensor_1d = tf.range(5)  # Creates a tensor: [0, 1, 2, 3, 4]
print("1D Tensor:", tensor_1d.numpy())  # Convert to numpy and print

1D Tensor: [0 1 2 3 4]


In [6]:
# Create a 2D tensor (matrix) with shape (2, 3)
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])  # Creates a tensor: [[1, 2, 3], [4, 5, 6]]
print("2D Tensor:\n", tensor_2d.numpy())  # Convert to numpy and print

2D Tensor:
 [[1 2 3]
 [4 5 6]]


In [7]:
# Performing arithmetic operations
# Adding a scalar to a tensor
tensor_add = tensor_2d + 10  # Adds 10 to each element
print("Tensor after adding 10:\n", tensor_add.numpy())  # Print the result

Tensor after adding 10:
 [[11 12 13]
 [14 15 16]]


In [8]:
# Element-wise multiplication
tensor_mul = tensor_2d * 2  # Multiplies each element by 2
print("Tensor after multiplying by 2:\n", tensor_mul.numpy())  # Print the result

Tensor after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]]


In [9]:
# Basic tensor manipulation
# Reshaping the 2D tensor to a 1D tensor
tensor_reshaped = tf.reshape(tensor_2d, [6])  # Reshape to a vector of size 6
print("Reshaped Tensor:", tensor_reshaped.numpy())  # Print the reshaped tensor

Reshaped Tensor: [1 2 3 4 5 6]


In [10]:
# Indexing a tensor
# Access the element at row 1, column 2 (zero-indexed)
element = tensor_2d[1, 2]  # Access element at 2nd row and 3rd column
print("Element at (1, 2):", element.numpy())  # Print the accessed element

Element at (1, 2): 6


## pytorch

In [11]:
# Importing the PyTorch library
import torch  # Import PyTorch

In [12]:
# Creating tensors
# Create a 1D tensor (vector) with values from 0 to 4
tensor_1d = torch.arange(5)  # Creates a tensor: [0, 1, 2, 3, 4]
print("1D Tensor:", tensor_1d.numpy())  # Convert to numpy and print

1D Tensor: [0 1 2 3 4]


In [13]:
# Create a 2D tensor (matrix) with shape (2, 3)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Creates a tensor: [[1, 2, 3], [4, 5, 6]]
print("2D Tensor:\n", tensor_2d.numpy())  # Convert to numpy and print

2D Tensor:
 [[1 2 3]
 [4 5 6]]


In [14]:
# Performing arithmetic operations
# Adding a scalar to a tensor
tensor_add = tensor_2d + 10  # Adds 10 to each element
print("Tensor after adding 10:\n", tensor_add.numpy())  # Print the result

Tensor after adding 10:
 [[11 12 13]
 [14 15 16]]


In [15]:
# Element-wise multiplication
tensor_mul = tensor_2d * 2  # Multiplies each element by 2
print("Tensor after multiplying by 2:\n", tensor_mul.numpy())  # Print the result

Tensor after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]]


In [16]:
# Basic tensor manipulation
# Reshaping the 2D tensor to a 1D tensor
tensor_reshaped = tensor_2d.view(6)  # Reshape to a vector of size 6
print("Reshaped Tensor:", tensor_reshaped.numpy())  # Print the reshaped tensor

Reshaped Tensor: [1 2 3 4 5 6]


In [17]:
# Indexing a tensor
# Access the element at row 1, column 2 (zero-indexed)
element = tensor_2d[1, 2]  # Access element at 2nd row and 3rd column
print("Element at (1, 2):", element.numpy())  # Print the accessed element

Element at (1, 2): 6
